FROM triumfmlutils/baseml:v0.2

LABEL maintainer="klaberinto@triumf.ca"

RUN pip install bdata

#Installing JupyterLab, if not already installed
RUN pip install jupyterlab

# Installing Jupyter Widgets
RUN pip install ipywidgets
RUN jupyter nbextension enable --py widgetsnbextension

# Installing NODE JS required for JupyterLab Widgets Extension
# https://github.com/nodesource/distributions/blob/master/README.md#deb
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

#Installing JypyterLab Widgets Extension
#https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension
RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
