FROM triumfmlutils/baseml:v0.2

LABEL maintainer="klaberinto@triumf.ca"

#Install Connector/Python for MySQL for MuSR MUD database
#https://dev.mysql.com/doc/connector-python/en/connector-python-installation-binary.html
RUN pip install mysql-connector-python

#Install bdata for mudpy for MUD file manipulation/reading
RUN pip install 'bdata==2.1.0'

#Installing JupyterLab, if not already installed
RUN pip install jupyterlab

# Installing Jupyter Widgets
RUN pip install ipywidgets
RUN jupyter nbextension enable --py widgetsnbextension

# Installing NODE JS required for JupyterLab Widgets Extension
# https://github.com/nodesource/distributions/blob/master/README.md#deb
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

#Installing JypyterLab Widgets Extension
#https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension
RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38

# Install pandoc for Jupyter Notebook Conversion
# https://nbconvert.readthedocs.io/en/latest/install.html#installing-pandoc
RUN apt-get install pandoc
